// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Eugene Berger",
            "url": "https://f1bonacc1.github.io/process-compose/"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hostname": {
            "get": {
                "description": "Get process compose hostname",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hostname"
                ],
                "summary": "Get Hostname",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Check if server is responding",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Liveness"
                ],
                "summary": "Liveness Check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/process": {
            "post": {
                "description": "Update porcess",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Updates process configuration",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/process/info/{name}": {
            "get": {
                "description": "Retrieves the given process and its config",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Get process config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Process Config",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/process/logs/{name}/{endOffset}/{limit}": {
            "get": {
                "description": "Retrieves the process logs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Get process logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset from the end of the log",
                        "name": "endOffset",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit of lines to get (0 will get all the lines till the end)",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Process Logs",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/process/ports/{name}": {
            "get": {
                "description": "Retrieves process open ports",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Get process ports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Process Ports",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/process/restart/{name}": {
            "post": {
                "description": "Restarts the process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Restart a process",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Restarted Process Name",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/process/scale/{name}/{scale}": {
            "patch": {
                "description": "Scale a process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Scale a process to a given replicas count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "New amount of process replicas",
                        "name": "scale",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scaled Process Name",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/process/start/{name}": {
            "post": {
                "description": "Starts the process if the state is not 'running' or 'pending'",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Start a process",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Started Process Name",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/process/stop/{name}": {
            "patch": {
                "description": "Sends kill signal to the process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Stop a process",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stopped Process Name",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/process/{name}": {
            "get": {
                "description": "Retrieves the given process and its status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Get process state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Process Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Process State",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/processes": {
            "get": {
                "description": "Retrieves all the configured processes and their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Get all processes",
                "responses": {
                    "200": {
                        "description": "Processes Status",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/processes/stop": {
            "patch": {
                "description": "Sends kill signal to the processes list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Process"
                ],
                "summary": "Stop processes",
                "parameters": [
                    {
                        "description": "Processes Names",
                        "name": "[]string",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stopped Processes Names",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project": {
            "post": {
                "description": "Update running project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Updates running processes",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/state": {
            "get": {
                "description": "Retrieves project state information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Get project state",
                "responses": {
                    "200": {
                        "description": "Project State",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/project/stop": {
            "post": {
                "description": "Shuts down the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Stops all the processes and the server",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Process Compose API",
	Description:      "This is a sample server Process Compose server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
