version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocyclo
    - goheader
    - gomodguard
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
