version: "0.5"
log_level: debug
processes:
  process0:
    command: "ls ddd"

  process1:
    command: "powershell.exe ./test_loop.ps1 ${PROC4}"
    availability:
      restart: "on_failure"
      backoff_seconds: 2
    depends_on:
      process2:
        condition: process_completed_successfully
      process3:
        condition: process_completed
      # process4:
      #   condition: process_completed_successfully
    environment:
      - 'EXIT_CODE=0'

  process2:
    command: "powershell.exe ./test_loop.ps1 process2"
    log_location: ./pc.proc2.log
    availability:
      restart: "on_failure"
    # depends_on:
    #   process3:
    #     condition: process_completed_successfully
    environment:
      - 'ABC=2221'
      - 'PRINT_ERR=111'
      - 'EXIT_CODE=0'

  process3:
    command: "powershell.exe ./test_loop.ps1 process3"
    availability:
      restart: "on_failure"
      backoff_seconds: 2
    depends_on:
      process4:
        condition: process_completed_successfully

  process4:
    command: "powershell.exe ./test_loop.ps1 process4"
    # availability:
    #   restart: on_failure
    environment:
      - 'ABC=2221'
      - 'EXIT_CODE=1'

  kcalc:
    command: "calc"
    disabled: true

environment:
  - 'ABC=222'
log_location: ./pc.log
