[package]
name = "process-compose-openapi-client"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
progenitor = { git = "https://github.com/oxidecomputer/progenitor" }
reqwest = { version = "^0.12", default-features = false, features = ["json", "stream"] }
serde = { version = "1.0.42", default-features = false, features = ["derive"] }


[dev-dependencies]
tokio = { version = "1.4", features = ["macros"]}
