// Code generated by "stringer -type=MonitorFor"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonitorForNone-0]
	_ = x[MonitorForActivity-1]
	_ = x[MonitorForSilence-2]
}

const _MonitorFor_name = "MonitorForNoneMonitorForActivityMonitorForSilence"

var _MonitorFor_index = [...]uint8{0, 14, 32, 49}

func (i MonitorFor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MonitorFor_index)-1 {
		return "MonitorFor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitorFor_name[_MonitorFor_index[idx]:_MonitorFor_index[idx+1]]
}
