// Code generated by "stringer -type=ProcessCondition"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcessConditionCompleted-0]
	_ = x[ProcessConditionCompletedSuccessfully-1]
	_ = x[ProcessConditionHealthy-2]
	_ = x[ProcessConditionStarted-3]
	_ = x[ProcessConditionLogReady-4]
}

const _ProcessCondition_name = "ProcessConditionCompletedProcessConditionCompletedSuccessfullyProcessConditionHealthyProcessConditionStartedProcessConditionLogReady"

var _ProcessCondition_index = [...]uint8{0, 25, 62, 85, 108, 132}

func (i ProcessCondition) String() string {
	if i < 0 || i >= ProcessCondition(len(_ProcessCondition_index)-1) {
		return "ProcessCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessCondition_name[_ProcessCondition_index[i]:_ProcessCondition_index[i+1]]
}
