// Code generated by "stringer -type=RestartPolicy"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RestartPolicyNo-0]
	_ = x[RestartPolicyAlways-1]
	_ = x[RestartPolicyOnFailure-2]
	_ = x[RestartPolicyExitOnFailure-3]
}

const _RestartPolicy_name = "RestartPolicyNoRestartPolicyAlwaysRestartPolicyOnFailureRestartPolicyExitOnFailure"

var _RestartPolicy_index = [...]uint8{0, 15, 34, 56, 82}

func (i RestartPolicy) String() string {
	if i < 0 || i >= RestartPolicy(len(_RestartPolicy_index)-1) {
		return "RestartPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RestartPolicy_name[_RestartPolicy_index[i]:_RestartPolicy_index[i+1]]
}
